# Generated by Django 6.0.6 on 2026-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='group',
            field=models.CharField(choices=[('CUSTOMER CARE', 'Customer Care'), ('INFORMATION', 'Information')], default='CUSTOMER CARE', max_length=50),
        ),
    ]
