# Generated by Django 6.0.6 on 2026-09-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_contactmessage_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('replied', 'Replied')], default='unread', max_length=20),
        ),
    ]
