# Generated by Django 6.0.6 on 2026-09-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='variants',
            field=models.JSONField(blank=True, default=dict, help_text="Stores paths to generated variants (e.g. {'card': 'path', 'thumb': 'path'})"),
        ),
    ]
