# Generated by Django 6.0.6 on 2026-07-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='apple_touch_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_apple_icon', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_header_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_email_logo', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_footer_logo', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_login_logo', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_main_logo', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_navbar_logo', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='preloader_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_preloader_logo', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_sharing_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_social_image', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sticky_navbar_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_sticky_logo', to='media.media'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_favicon', to='media.media'),
        ),
    ]
