# Generated by Django 6.0.6 on 2026-07-09 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesettings_logo_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_bg', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_center_button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_center_button_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('ghost', 'Ghost')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_center_button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_height',
            field=models.CharField(default='100vh', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_highlight_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_left_button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_left_button_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('ghost', 'Ghost')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_left_button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_left_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_left', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_left_image_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_mobile_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_mobile_bg', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_mobile_height',
            field=models.CharField(default='70vh', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_mobile_left_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_mobile_left', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_mobile_right_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_mobile_right', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_overlay_opacity',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_right_button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_right_button_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('ghost', 'Ghost')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_right_button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_right_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_right', to='media.media'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_right_image_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_small_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_vid', to='media.media'),
        ),
    ]
