# Generated by Django 6.0.6 on 2026-07-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_hero_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_embed_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_profile_url',
            field=models.URLField(blank=True),
        ),
    ]
