"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

import sys
import environ
import os
import urllib.parse
from pathlib import Path
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Python path mein 'apps' folder ko add karna taake apps direct call ho sakein
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

env = environ.Env()

# Try to read from .env file if it exists (local development)
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = env('SECRET_KEY', default='django-insecure-key-change-in-production')
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', 'testserver', '.vercel.app', 'tawakkal.store', '.tawakkal.store'])

# Application definition
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',  # Ensures WhiteNoise handles admin static assets gracefully
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    
    # Local Apps
    'apps.core',
    'apps.users',
    'apps.audit',
    'media',          # <-- Yahan direct 'media' kar diya taake dependency issue solve ho jaye
    'apps.catalog',
    'apps.customers',
    'apps.orders',
    'apps.payments',
    'apps.shipping',
    'apps.analytics',
    'apps.cms',
    'apps.surveys',
    'apps.stores',
    'apps.notifications',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'apps.core.middleware.TracebackMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
CORS_ALLOWED_ORIGINS.extend([
    'https://tawakkal-frontend.vercel.app',
    'http://localhost:5173',
    'http://localhost:3000',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:3000',
    'https://tawakkal.store',
    'https://www.tawakkal.store'
])
# Ensure uniqueness
CORS_ALLOWED_ORIGINS = list(set(CORS_ALLOWED_ORIGINS))

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
CSRF_TRUSTED_ORIGINS.extend([
    'https://tawakkal-frontend.vercel.app',
    'https://tawakkal-backend-teal.vercel.app',
    'https://tawakkal.store',
    'https://www.tawakkal.store'
])
CSRF_TRUSTED_ORIGINS = list(set(CSRF_TRUSTED_ORIGINS))

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database configuration
db_url = env('DATABASE_URL', default='')
has_db_env = env('DB_NAME', default='') or env('DB_USER', default='')

if db_url:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=db_url,
            conn_max_age=600,
        )
    }
elif has_db_env:
    db_name = env('DB_NAME')
    db_user = env('DB_USER')
    db_password = env('DB_PASSWORD', default='')
    db_host = env('DB_HOST', default='localhost')
    db_port = env('DB_PORT', default='3306')
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
        }
    }
elif DEBUG:
    # Local development fallback to SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Fallback to direct MySQL settings if DATABASE_URL is not set (Live production)
    db_name = env('DB_NAME', default='sql_tawakkal_store')
    db_user = env('DB_USER', default='sql_tawakkal_store')
    db_password = env('DB_PASSWORD', default='613e0ce6dc83f')
    db_host = env('DB_HOST', default='localhost')
    db_port = env('DB_PORT', default='3306')
    
<<<<<<< HEAD
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
=======
    if db_url:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.config(
                default=db_url,
                conn_max_age=600,
            )
        }
    else:
        # Fallback to direct MySQL settings if DATABASE_URL is not set
        db_name = env('DB_NAME', default='sql_tawakkal_store')
        db_user = env('DB_USER', default='sql_tawakkal_store')
        db_password = env('DB_PASSWORD', default='613e0ce6dc83f')
        db_host = env('DB_HOST', default='localhost')
        db_port = env('DB_PORT', default='3306')
        
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': db_name,
                'USER': db_user,
                'PASSWORD': db_password,
                'HOST': db_host,
                'PORT': db_port,
                'OPTIONS': {
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                }
>>>>>>> 6de244e60cebd812828a5b55d0ed2bc32f1a0aa1
            }
        }
    }


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []

# Use CompressedStaticFilesStorage or standard StaticFilesStorage. 
# ManifestStaticFilesStorage causes 500 errors on serverless because the manifest isn't shared across builders.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Required for Vercel to recognize HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'apps.core.exceptions.custom_exception_handler',
    'DEFAULT_RENDERER_CLASSES': (
        'apps.core.renderers.StandardizedJSONRenderer',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 25,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Tawakkal Luxury API',
    'DESCRIPTION': 'Backend API for Tawakkal Luxury Admin Dashboard',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# Production logging — sends complete tracebacks to stdout/stderr for Vercel Runtime Logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module}.{funcName}:{lineno} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
# Email Configuration
import ssl
from django.core.mail.backends.smtp import EmailBackend as SmtpEmailBackend

class UnverifiedSmtpEmailBackend(SmtpEmailBackend):
    @property
    def ssl_context(self):
        context = ssl.create_default_context()
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
        return context

EMAIL_BACKEND = 'config.settings.UnverifiedSmtpEmailBackend'

<<<<<<< HEAD
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'mail.tawakkal.store')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'info@tawakkal.store')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
=======
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
>>>>>>> 6de244e60cebd812828a5b55d0ed2bc32f1a0aa1
