# Generated by Django 6.0.6 on 2026-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='map_link',
            field=models.URLField(blank=True, help_text='Google Maps authoritative link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='timing',
            field=models.CharField(blank=True, help_text='Store timings (e.g. 10:00 AM - 8:00 PM)', max_length=255, null=True),
        ),
    ]
