# Generated by Django 6.0.6 on 2026-07-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='stores.warehouse'),
        ),
    ]
