# Generated by Django 6.0.6 on 2026-07-09 20:43

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify

def migrate_brands(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    Brand = apps.get_model('catalog', 'Brand')
    
    # Iterate through all products that have a non-empty text brand
    for product in Product.objects.exclude(brand__exact=''):
        brand_name = product.brand.strip()
        if not brand_name:
            continue
            
        slug = slugify(brand_name)
        # Handle duplicate slugs gracefully
        original_slug = slug
        counter = 1
        while True:
            try:
                brand_obj, created = Brand.objects.get_or_create(
                    slug=slug,
                    defaults={'name': brand_name}
                )
                break
            except Exception:
                slug = f"{original_slug}-{counter}"
                counter += 1
                
        product.brand_fk = brand_obj
        product.save(update_fields=['brand_fk'])

def reverse_migrate_brands(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for product in Product.objects.all():
        if product.brand_fk:
            product.brand = product.brand_fk.name
            product.save(update_fields=['brand'])

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_badge_product_badges_brand_category_brand_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_brands, reverse_migrate_brands),
    ]
