# Generated by Django 6.0.6 on 2026-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_brand_fk_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shipping cost for this product', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
