# Generated by Django 6.0.6 on 2026-07-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_article_no_product_shipping_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wholesale_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_min_quantity',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_step_quantity',
            field=models.IntegerField(default=6),
        ),
    ]
